apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: caliper
  name: caliper
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: caliper
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: caliper
    spec:
      containers:
        - args:
            - launch
            - manager
          env:
            - name: CALIPER-FLOW-SKIP-INSTALL
              value: "true"
            - name: CALIPER_BENCHCONFIG
              value: benchmarks/scenario/simple/config.yaml
            - name: CALIPER_BIND_SUT
              value: besu:latest
            - name: CALIPER_NETWORKCONFIG
              value: networks/networkconfig.json
          image: hyperledger/caliper:0.4.2
          name: caliper
          volumeMounts:
            - mountPath: /hyperledger/caliper/workspace
              name: caliper-cm0
          workingDir: /hyperledger/caliper/workspace
      restartPolicy: Always
      volumes:
        - configMap:
            name: caliper-cm0
          name: caliper-cm0
